<a href="https://colab.research.google.com/github/vs334749-pixel/IPL-Dataset-Analysis/blob/main/IPL_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IPL_Dataset_Missing_Values.csv")
df.head()

,Match_ID,Team,Opponent,Venue,Runs,Wickets,Overs,Winner,Player_of_Match,Strike_Rate
0,1,SRH,SRH,NaN,134.0,8.0,19.6,GT,Player_14,185.4
1,2,MI,KKR,Jaipur,215.0,8.0,17.8,GT,Player_14,189.9
2,3,DC,SRH,Mumbai,217.0,NaN,18.1,GT,Player_15,140.7
3,4,LSG,DC,Bengaluru,137.0,2.0,20.0,DC,Player_9,133.4
4,5,KKR,RCB,Jaipur,230.0,7.0,17.2,RCB,Player_10,143.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Match_ID         30 non-null     int64
 1   Team             30 non-null     object
 2   Opponent         28 non-null     object
 3   Venue            26 non-null     object
 4   Runs             29 non-null     float64
 5   Wickets          27 non-null     float64
 6   Overs            29 non-null     float64
 7   Winner           29 non-null     object
 8   Player_of_Match  29 non-null     object
 9   Strike_Rate      28 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 2.5+ KB

In [6]:
df.isnull().sum()

Match_ID           0
Team               0
Opponent           2
Venue              4
Runs               1
Wickets            3
Overs              1
Winner             1
Player_of_Match    1
Strike_Rate        2
dtype: int64

In [7]:
total_missing = df.isnull().sum().sum()
print("total missing values:",total_missing)

total missing values: 15

In [8]:
null_rows = df[df.isnull().any(axis=1)]
print(null_rows)

    Match_ID  Team Opponent      Venue   Runs  Wickets  Overs Winner  \
0          1   SRH      SRH        NaN  134.0      8.0   19.6     GT
2          3    DC      SRH     Mumbai  217.0      NaN   18.1     GT
5          6   SRH      SRH     Jaipur  124.0      NaN   15.2    CSK
6          7    GT      NaN    Chennai  230.0      3.0   15.4     GT
12        13    MI      KKR        NaN  187.0      NaN   17.1    KKR
16        17   RCB      LSG        NaN  187.0      3.0   17.9    SRH
18        19    MI     PBKS      Delhi  207.0     10.0   15.3     GT
21        22   SRH      CSK        NaN  209.0      7.0   19.7    CSK
24        25  PBKS      NaN     Mumbai    NaN      2.0   15.4     RR
26        27    RR       DC    Chennai  171.0      4.0    NaN    NaN
27        28    GT       DC  Bengaluru  202.0      5.0   16.9     RR

   Player_of_Match  Strike_Rate
0        Player_14        185.4
2        Player_15        140.7
5        Player_10        206.3
6         Player_8        115.7
12       Player_12        193.2
16             NaN        121.7
18       Player_15          NaN
21       Player_11        158.1
24       Player_11        189.6
26       Player_11        137.4
27        Player_4          NaN

In [9]:
df_clean = df.dropna()

In [10]:
print(df_clean.isnull().sum())

Match_ID           0
Team               0
Opponent           0
Venue              0
Runs               0
Wickets            0
Overs              0
Winner             0
Player_of_Match    0
Strike_Rate        0
dtype: int64

In [11]:
print("Original Rows:", len(df))
print("Rows After Cleaning:", len(df_clean))

Original Rows: 30
Rows After Cleaning: 19

In [12]:
df_clean.to_csv("IPL_Dataset_Cleaned.csv", index=False)
print("Dataset cleaned successfully!")

Dataset cleaned successfully!

Fill Missing Values Automatically

# Fill numerical columns with mean

In [13]:
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Match_ID           0
Team               0
Opponent           2
Venue              4
Runs               1
Wickets            3
Overs              1
Winner             1
Player_of_Match    1
Strike_Rate        2
dtype: int64

In [14]:
df["Runs"] = df["Runs"].fillna(df["Runs"].mean())
df["Wickets"] = df["Wickets"].fillna(df["Wickets"].mean())
df["Overs"] = df["Overs"].fillna(df["Overs"].mean())
df["Strike_Rate"] = df["Strike_Rate"].fillna(df["Strike_Rate"].mean())

In [15]:
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Match_ID           0
Team               0
Opponent           2
Venue              4
Runs               0
Wickets            0
Overs              0
Winner             1
Player_of_Match    1
Strike_Rate        0
dtype: int64

In [16]:
df.to_csv("IPL_Dataset_Auto_Cleaned.csv", index=False)

# **The 10 Questions and Answers**

# 1. Which team has the highest average strike rate and what is its average runs?

In [28]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

result = df.groupby("Team").agg({
    "Strike_Rate":"mean",
    "Runs":"mean"
}).sort_values("Strike_Rate",ascending=False)

print(result.head(1))

      Strike_Rate   Runs
Team
SRH        180.22  149.2

# 2. Find the Top 5 players with the highest average strike rate.

In [29]:
top_players = df.groupby("Player_of_Match")["Strike_Rate"] \
.mean() \
.sort_values(ascending=False) \
.head(5)

print(top_players)

Player_of_Match
Player_14    187.650000
Player_1     186.300000
Player_10    161.733333
Player_15    156.735119
Player_12    153.600000
Name: Strike_Rate, dtype: float64

# 3. Which team wins most matches at each venue?

In [30]:
result = df.groupby(["Venue","Winner"]).size()

print(result)

Venue      Winner
Ahmedabad  KKR       1
           MI        1
           PBKS      1
           RCB       1
           SRH       1
Bengaluru  DC        1
           KKR       1
           RCB       1
           RR        1
Chennai    GT        1
           KKR       1
Delhi      GT        1
Hyderabad  KKR       1
Jaipur     CSK       1
           GT        1
           KKR       1
           LSG       1
           PBKS      1
           RCB       1
Kolkata    GT        1
           RCB       1
Mumbai     CSK       1
           GT        1
           RCB       1
           RR        1
dtype: int64

# 5. Find matches where Runs are above average AND Strike Rate is above average.

In [31]:
result = df[
(df["Runs"]>df["Runs"].mean()) &
(df["Strike_Rate"]>df["Strike_Rate"].mean())
]

print(result)

    Match_ID Team Opponent      Venue   Runs  Wickets  Overs Winner  \
1          2   MI      KKR     Jaipur  215.0      8.0   17.8     GT
9         10  CSK      LSG  Ahmedabad  196.0      8.0   19.5    KKR
14        15   RR      CSK     Jaipur  219.0      7.0   16.2    KKR
21        22  SRH      CSK        NaN  209.0      7.0   19.7    CSK

   Player_of_Match  Strike_Rate
1        Player_14        189.9
9         Player_1        186.3
14       Player_15        152.5
21       Player_11        158.1

# 6.Find the Top 3 Teams with the Highest Average Strike Rate and More Than 2 Matches

In [32]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

result = (
    df.groupby("Team")
      .agg(
          Matches=("Match_ID", "count"),
          Avg_Strike_Rate=("Strike_Rate", "mean")
      )
)

result = result[result["Matches"] > 2]

print(result.sort_values("Avg_Strike_Rate", ascending=False).head(3))

      Matches  Avg_Strike_Rate
Team
SRH         5       180.220000
MI          3       177.003571
PBKS        3       152.733333

# 7.Find the Team That Has Won the Most Matches at Each Venue

In [34]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

result = (
    df.groupby(["Venue", "Winner"])
      .size()
      .reset_index(name="Wins")
)

idx = result.groupby("Venue")["Wins"].idxmax()

print(result.loc[idx])

        Venue Winner  Wins
0   Ahmedabad    KKR     1
5   Bengaluru     DC     1
9     Chennai     GT     1
11      Delhi     GT     1
12  Hyderabad    KKR     1
13     Jaipur    CSK     1
19    Kolkata     GT     1
21     Mumbai    CSK     1

# 8.Find Teams Whose Average Runs Are Greater Than the Overall Average Runs

In [35]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

overall_avg = df["Runs"].mean()

team_avg = df.groupby("Team")["Runs"].mean()

print(team_avg[team_avg > overall_avg])

Team
CSK    216.500000
DC     209.750000
GT     190.500000
KKR    219.000000
MI     203.000000
RCB    199.000000
RR     201.666667
Name: Runs, dtype: float64

# 9.Create a New Performance Index and Find the Best Match

In [36]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

df["Performance_Index"] = (
    df["Runs"] * df["Strike_Rate"]
) / df["Overs"]

best_match = df.loc[df["Performance_Index"].idxmax()]

print(best_match)

Match_ID                      25
Team                        PBKS
Opponent                     NaN
Venue                     Mumbai
Runs                  188.448276
Wickets                      2.0
Overs                       15.4
Winner                        RR
Player_of_Match        Player_11
Strike_Rate                189.6
Performance_Index    2320.116435
Name: 24, dtype: object

# 10.Generate a Complete Team Performance Dashboard-

In [37]:
import pandas as pd

df = pd.read_csv("IPL_Dataset_Auto_Cleaned.csv")

dashboard = df.groupby("Team").agg({
    "Runs": ["sum", "mean", "max", "min"],
    "Wickets": ["sum", "mean"],
    "Overs": ["mean"],
    "Strike_Rate": ["mean", "max"],
    "Match_ID": "count"
})

print(dashboard)

            Runs                                   Wickets            \
             sum        mean         max    min        sum      mean
Team
CSK   433.000000  216.500000  237.000000  196.0  16.000000  8.000000
DC    839.000000  209.750000  226.000000  187.0  23.740741  5.935185
GT    762.000000  190.500000  230.000000  128.0  19.000000  4.750000
KKR   438.000000  219.000000  230.000000  208.0  12.000000  6.000000
LSG   276.000000  138.000000  139.000000  137.0   7.000000  3.500000
MI    609.000000  203.000000  215.000000  187.0  23.740741  7.913580
PBKS  547.448276  182.482759  188.448276  175.0  12.000000  4.000000
RCB   398.000000  199.000000  211.000000  187.0   9.000000  4.500000
RR    605.000000  201.666667  219.000000  171.0  21.000000  7.000000
SRH   746.000000  149.200000  209.000000  122.0  28.740741  5.748148

          Overs Strike_Rate        Match_ID
           mean        mean    max    count
Team
CSK   17.850000  151.450000  186.3        2
DC    17.475000  125.200000  140.7        4
GT    16.850000  137.977679  152.6        4
KKR   16.850000  142.750000  143.0        2
LSG   17.600000  130.650000  133.4        2
MI    16.733333  177.003571  193.2        3
PBKS  16.566667  152.733333  189.6        3
RCB   18.150000  122.200000  122.7        2
RR    16.362069  133.400000  152.5        3
SRH   18.280000  180.220000  211.0        5