<a href="https://colab.research.google.com/github/vs334749-pixel/IPL-Dataset-Analysis/blob/main/IPL_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IPL_Dataset_Missing_Values.csv")
df.head()

,Match_ID,Team,Opponent,Venue,Runs,Wickets,Overs,Winner,Player_of_Match,Strike_Rate
0,1,SRH,SRH,NaN,134.0,8.0,19.6,GT,Player_14,185.4
1,2,MI,KKR,Jaipur,215.0,8.0,17.8,GT,Player_14,189.9
2,3,DC,SRH,Mumbai,217.0,NaN,18.1,GT,Player_15,140.7
3,4,LSG,DC,Bengaluru,137.0,2.0,20.0,DC,Player_9,133.4
4,5,KKR,RCB,Jaipur,230.0,7.0,17.2,RCB,Player_10,143.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Match_ID         30 non-null     int64
 1   Team             30 non-null     object
 2   Opponent         28 non-null     object
 3   Venue            26 non-null     object
 4   Runs             29 non-null     float64
 5   Wickets          27 non-null     float64
 6   Overs            29 non-null     float64
 7   Winner           29 non-null     object
 8   Player_of_Match  29 non-null     object
 9   Strike_Rate      28 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 2.5+ KB

In [4]:
df.isnull().sum()

Match_ID           0
Team               0
Opponent           2
Venue              4
Runs               1
Wickets            3
Overs              1
Winner             1
Player_of_Match    1
Strike_Rate        2
dtype: int64

In [6]:
total_missing = df.isnull().sum().sum()
print("total missing values:",total_missing)

total missing values: 15

In [7]:
null_rows = df[df.isnull().any(axis=1)]
print(null_rows)

    Match_ID  Team Opponent      Venue   Runs  Wickets  Overs Winner  \
0          1   SRH      SRH        NaN  134.0      8.0   19.6     GT
2          3    DC      SRH     Mumbai  217.0      NaN   18.1     GT
5          6   SRH      SRH     Jaipur  124.0      NaN   15.2    CSK
6          7    GT      NaN    Chennai  230.0      3.0   15.4     GT
12        13    MI      KKR        NaN  187.0      NaN   17.1    KKR
16        17   RCB      LSG        NaN  187.0      3.0   17.9    SRH
18        19    MI     PBKS      Delhi  207.0     10.0   15.3     GT
21        22   SRH      CSK        NaN  209.0      7.0   19.7    CSK
24        25  PBKS      NaN     Mumbai    NaN      2.0   15.4     RR
26        27    RR       DC    Chennai  171.0      4.0    NaN    NaN
27        28    GT       DC  Bengaluru  202.0      5.0   16.9     RR

   Player_of_Match  Strike_Rate
0        Player_14        185.4
2        Player_15        140.7
5        Player_10        206.3
6         Player_8        115.7
12       Player_12        193.2
16             NaN        121.7
18       Player_15          NaN
21       Player_11        158.1
24       Player_11        189.6
26       Player_11        137.4
27        Player_4          NaN

In [8]:
df_clean = df.dropna()

In [9]:
print(df_clean.isnull().sum())

Match_ID           0
Team               0
Opponent           0
Venue              0
Runs               0
Wickets            0
Overs              0
Winner             0
Player_of_Match    0
Strike_Rate        0
dtype: int64

In [10]:
print("Original Rows:", len(df))
print("Rows After Cleaning:", len(df_clean))

Original Rows: 30
Rows After Cleaning: 19

In [12]:
df_clean.to_csv("IPL_Dataset_Cleaned.csv", index=False)
print("Dataset cleaned successfully!")

Dataset cleaned successfully!

Fill Missing Values Automatically

# Fill numerical columns with mean

In [19]:
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Match_ID           0
Team               0
Opponent           0
Venue              0
Runs               1
Wickets            3
Overs              1
Winner             0
Player_of_Match    0
Strike_Rate        2
dtype: int64

In [20]:
df["Runs"] = df["Runs"].fillna(df["Runs"].mean())
df["Wickets"] = df["Wickets"].fillna(df["Wickets"].mean())
df["Overs"] = df["Overs"].fillna(df["Overs"].mean())
df["Strike_Rate"] = df["Strike_Rate"].fillna(df["Strike_Rate"].mean())

In [21]:
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Match_ID           0
Team               0
Opponent           0
Venue              0
Runs               0
Wickets            0
Overs              0
Winner             0
Player_of_Match    0
Strike_Rate        0
dtype: int64

In [22]:
df.to_csv("IPL_Dataset_Auto_Cleaned.csv", index=False)